// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1FbPvnRhuzcOAydHa4_48zz4L63PzR4',
    appId: '1:254944676803:web:29fef1418e3a5b1bd5cb76',
    messagingSenderId: '254944676803',
    projectId: 'depi-todo-app',
    authDomain: 'depi-todo-app.firebaseapp.com',
    storageBucket: 'depi-todo-app.firebasestorage.app',
    measurementId: 'G-THHPF80M86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpaeD-GjIaSriPvKHf86SjLR9uCIhVgM',
    appId: '1:254944676803:android:69af7d7e2b51776ad5cb76',
    messagingSenderId: '254944676803',
    projectId: 'depi-todo-app',
    storageBucket: 'depi-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD3ty7dobeR6XIEFHDahpR2WCW7b7KH0s',
    appId: '1:254944676803:ios:914a56c2b342313dd5cb76',
    messagingSenderId: '254944676803',
    projectId: 'depi-todo-app',
    storageBucket: 'depi-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.depiNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD3ty7dobeR6XIEFHDahpR2WCW7b7KH0s',
    appId: '1:254944676803:ios:914a56c2b342313dd5cb76',
    messagingSenderId: '254944676803',
    projectId: 'depi-todo-app',
    storageBucket: 'depi-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.depiNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb1FbPvnRhuzcOAydHa4_48zz4L63PzR4',
    appId: '1:254944676803:web:5147c5a7078ba140d5cb76',
    messagingSenderId: '254944676803',
    projectId: 'depi-todo-app',
    authDomain: 'depi-todo-app.firebaseapp.com',
    storageBucket: 'depi-todo-app.firebasestorage.app',
    measurementId: 'G-89K7LDD3XS',
  );
}
